  version: '2.0'
  services:

    #PHP Service
    app:
      build:
        context: .
        dockerfile: ./docker/php-fpm/Dockerfile
      container_name: app
      restart: unless-stopped
      tty: true
      environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
      working_dir: /var/www/html/
      volumes:
        - ./:/var/www/html/
      networks:
        - app-network

    #Nginx Service
    webserver:
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped
      tty: true
      ports:
        - "8082:80"
        - "443:443"
      volumes:
        - ./:/var/www/html/
        - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      networks:
        - app-network

    #MySQL Service
    database:
      image: postgres
      container_name: database
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - ./docker/postgres/data:/var/lib/postgresql/data
      ports:
        - '5432:5432'

    adminer:
      image: adminer
      container_name: shop_adminer
      restart: always
      ports:
        - 6080:8080
      networks:
        - app-network

  #Docker Networks
  networks:
    app-network:
      driver: bridge
